version = 1
SPDX-PackageName = "tinyml"
SPDX-PackageSupplier = "https://github.com/v-kut/tinyml"

# code
[[annotations]]
path = ["**.py", "**.ipynb", "**.tflite"]
SPDX-FileType = "SOURCE"
SPDX-FileCopyrightText = "2026 Vsevolod Kutsyn <vkutsyn@uw.edu>"
SPDX-License-Identifier = "Apache-2.0"

# documentation
[[annotations]]
path = ["**.md", "**.pdf", "**.png"]
SPDX-FileType = "DOCUMENTATION"
SPDX-FileCopyrightText = "2026 Vsevolod Kutsyn <vkutsyn@uw.edu>"
SPDX-License-Identifier = "CC-BY-NC-4.0"

# config files
[[annotations]]
path = [
  "**.github/**",
  "**.gitignore",
  "**.gitattributes",
  "**.gitmodules",
  "lefthook.yml",
  ".zed/**",
  "labs/lab5/**.cc"
]
SPDX-FileType = "OTHER"
SPDX-FileCopyrightText = "2026 Vsevolod Kutsyn <vkutsyn@uw.edu>"
SPDX-License-Identifier = "CC0-1.0"
