"""Serialize a `QuantModel` into a C header the Arduino sketch compiles in.

Pure `const` data: no allocator, no parser, no runtime. Floats carry `%.9g` and an `f`
suffix, so the compiler stores exactly the bits NumPy quantized with. Fewer digits is
how a host emulator and its device silently stop agreeing.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

import numpy as np

from tinyml_racing.deploy.quantize import QuantModel

# `tinyml.h` refuses anything else, and `quantize.ACTIVATION` is why there is
# only one: the macro stays in the header as the cross-check that a `model.h`
# and a kernel were built for the same scheme.
ACTIVATION_MACRO = "TINYML_TANH"


def _f32(value) -> str:
    """A C float literal that round-trips to exactly `value` as binary32.

    `%.9g` renders 1.0 as "1", and "1f" is a syntax error, not a float literal.
    """
    v = np.float32(value)
    if not np.isfinite(v):
        raise ValueError(f"non-finite constant {v} in the quantized model")
    text = f"{v:.9g}"
    if not any(c in text for c in ".e"):
        text += ".0"
    return text + "f"


def _wrap(items) -> str:
    return textwrap.fill(
        ", ".join(items),
        width=92,
        initial_indent="    ",
        subsequent_indent="    ",
        break_long_words=False,
        break_on_hyphens=False,
    )


def _int8_array(name: str, data: np.ndarray) -> str:
    body = _wrap([str(int(v)) for v in data.reshape(-1)])
    return f"static const int8_t {name}[{data.size}] = {{\n{body}\n}};"


def _f32_array(name: str, data: np.ndarray) -> str:
    body = _wrap([_f32(v) for v in data.reshape(-1)])
    return f"static const float {name}[{data.size}] = {{\n{body}\n}};"


def emit_header(model: QuantModel, provenance: str = "") -> str:
    notes = "".join(f"// {line}\n" for line in provenance.splitlines())
    # MODEL_DIGEST is a checksum of the numbers, not of the file: reformatting
    # the header, or regenerating it from the same run, leaves it alone.
    parts: list[str] = [
        f"""// Generated by tinyml_racing.deploy.codegen, do not edit.
// actor {model.arch}, {model.activation}, int8 weights + int8 activations
// {model.n_weights} weights, {model.flash_bytes} bytes of constants here plus
// {model.deployed_flash_bytes - model.flash_bytes} bytes of tables in tinyml.h
{notes}
#pragma once
#include <stdint.h>

#define MODEL_N_LAYERS {len(model.layers)}
#define MODEL_N_IN {model.n_in}
#define MODEL_N_OUT {model.n_out}
#define MODEL_MAX_WIDTH {max(model.dims)}
#define MODEL_ACTIVATION {ACTIVATION_MACRO}
#define MODEL_CLIP {_f32(model.clip_action)}
#define MODEL_ARCH "{model.arch}"
#define MODEL_DIGEST 0x{model.digest():08x}u
"""
    ]

    for i, layer in enumerate(model.layers):
        n_in, n_out = layer.shape
        parts += [
            f"// layer {i}: {n_in} -> {n_out}",
            _int8_array(f"model_w{i}", layer.qw),
            _f32_array(f"model_m{i}", layer.mult),
            _f32_array(f"model_b{i}", layer.bias),
            "",
        ]

    # Parallel arrays rather than a struct-of-pointers literal: a plain aggregate
    # initializer stays in flash on every toolchain instead of being copied into
    # RAM at startup by some.
    n = len(model.layers)
    dims = ", ".join(str(d) for d in model.dims)
    inv_sx = ", ".join(_f32(layer.inv_input_scale) for layer in model.layers)
    ptr = {k: ", ".join(f"model_{k}{i}" for i in range(n)) for k in ("w", "m", "b")}
    parts.append(
        f"""static const uint16_t model_dims[{n + 1}] = {{{dims}}};
static const int8_t *const model_w[{n}] = {{{ptr["w"]}}};
static const float *const model_m[{n}] = {{{ptr["m"]}}};
static const float *const model_b[{n}] = {{{ptr["b"]}}};
static const float model_inv_sx[{n}] = {{{inv_sx}}};
"""
    )
    return "\n".join(parts)


def write_header(model: QuantModel, path: str | Path, provenance: str = "") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(emit_header(model, provenance))
    return path
